### ISSUE TITLE
Problem with UB

### ISSUE THREAD

**Issue by A5800000BD79867** [ziipzaaapM16A4/Default-AiCallouts-Pack#8]
STP has the opportunity to create a partner who will follow you in their car. When the AiCallouts calls the unit, then the partner behind the wheel accepts it and drives away, although it should not. (sry 4 my eng)

**Comment by ziipzaaapM16A4** [comment]
Do you have an example video, which you could provide?

**Comment by A5800000BD79867** [comment]
I will try.

**Comment by A5800000BD79867** [comment]
ty for waiting. [https://youtu.be/TIOVwxSczgw](url)

**Comment by ziipzaaapM16A4** [comment]
Ok. I do now understand the problem completely thanks to your video. 

It because STP does not use the lspdfr Funktion setCopToBusy() to signalize that this vehicle is currently in use of a script.

I will take a look if i could recognize a stp officer.

Thanks for your report. We will send a fix report here as soon as this bug has been fixed.

**Comment by ziipzaaapM16A4** [comment]
@A5800000BD79867 Can you send me you AmbientAICallouts Version number to verify which algorithm didn't work well?

**Comment by ziipzaaapM16A4** [comment]
@A5800000BD79867 
no i cant use PED:: GET_PED_GROUP_INDEX because it would return "cop" which is indeed a problem because i take for my callouts random lspdfr units.  if this function does not return that this is comming from an stop the ped script i cannot use it.

i searched for an api in stp but i didnt found a function which returns information wether a ped is comming from stp.

**Comment by ziipzaaapM16A4** [comment]
So possible fix has been found:

For your Ultimate Backup issue.. Have you considered checking which tasks an Ultimate Backup ped has when they're just standing around and using that to determine if they're busy?
If they have any extra tasks, they would be considered busy

**Comment by A5800000BD79867** [comment]
this may help 0xB0760331C7AA4155 or 0x77F1BEB8863288D5 but i can mistake

**Comment by ziipzaaapM16A4** [comment]
> this may help 0xB0760331C7AA4155 or 0x77F1BEB8863288D5 but i can mistake

Thank you. I already use successfully one of those natives to determine the tasks.

I just hadn't the time to identify tasks wich are specific to STP.

But since the last internal changes i am actually good at working with those task identifications and i am confident that if there are tasks, that we can fix it

**Comment by ziipzaaapM16A4** [comment]
@A5800000BD79867 okey it is true.

When STP controls the Driving:
CTaskDriveCarControl

When STP dismissed the ped:
CTaskDriveCarWander

@A5800000BD79867 okey it is true.

When STP controls the Driving:
CTaskDriveCarControl

When STP dismissed the ped:
CTaskDriveCarWander

**Comment by A5800000BD79867** [comment]
You also need to remember about the shootings, as well as the protection of suspects, if you do the functionality when the cops outside the car take a call. Of course, this is not the best way to find out, but what is there)

**Comment by ziipzaaapM16A4** [comment]
> You also need to remember about the shootings, as well as the protection of suspects, if you do the functionality when the cops outside the car take a call. Of course, this is not the best way to find out, but what is there)

They just use cops in vehicles when sirens turend off. so that would match to prision transport and following the player with sirens off.

**Comment by ziipzaaapM16A4** [comment]
Police Partner is a feature of Ultimate Backup.

**Comment by A5800000BD79867** [comment]
I looked at the UB updates. It seems like we added an API. I asked you to do this...
`isUltimateBackupCop()`

**Comment by ziipzaaapM16A4** [comment]
#

> I looked at the UB updates. It seems like we added an API. I asked them to do this...
> `isUltimateBackupCop()`

yes but then it would use only non UB cops which is also not good.
i guess i figured a good way to fix this without compleatly removing UB cops from the AmbientResponse vehicle selection.

**Comment by A5800000BD79867** [comment]
Why? I think that the native will return false if you release the partner

**Comment by ziipzaaapM16A4** [comment]
> Why? I think that the native will return false if you release the partner

Could you test this?

**Comment by ziipzaaapM16A4** [comment]
ok looks like they stay true when dismissed

**Comment by ziipzaaapM16A4** [comment]
**[fix] AmbientResponse using vehicles which are not free**
583d26c92363648b7d2586330e0ec05b6df9624c
